if(isDedicated) exitWith{};

player createDiarySubject ["patrol1","Patrol Brief"];
player createDiarySubject ["patrol2","Patrol Wiki"];

player createDiaryRecord ["patrol2", [ "Respawn" , "
When a player is killed they have the option to redepoly at the Base Medical Facility or at a deployed MHQ.
" ]];

player createDiaryRecord ["patrol2", [ "Redeploy" , "
Redploying is a way for a player to move to the battlefront quickly as long as there is an MHQ deployed.
<br/>
To Redploy: Die... OR Walk to the Flag near the Base Ammobox and select the Redeploy option, then select the MHQ
" ]];

player createDiaryRecord ["patrol2", [ "Recruit AI" , "
Recruiting additional AI units to a players Squad can be done at the Barracks<br/>
<br/>
To recruit units: select the option at the barracks and select from the unit types available<br/>
to dismiss units: walk up to the unit and select the ""Dismiss"" action to remove the unit from the battlefield<br/>
" ]];

player createDiaryRecord ["patrol2", [ "Rank" , "
The Ranking system allows players to rank up.<br/>
If gear restrictions is on, it will also limit the types and technology of the weapons available to the player in the ammoboxes.<br/>
By ranking up, a player can access better weapons and vehicles.<br/>
<br/>
To earn points towards a higher rank:<br/>
 - Stay with your team. Your proximity to team members will earn you points<br/>
 - Apply First Aid (AIS) to team members<br/>
 - Kill enemies. The bigger they are, the more you will earn<br/>
" ]];

player createDiaryRecord ["patrol2", [ "Towers" , "
Towers can be setup by moving the towers container to a location and selecting the ""Deploy Tower"" option to setup a tower<br/>
This is essential for a mission type.
" ]];

player createDiaryRecord ["patrol2", [ "Tasks" , "
Tasks are generated by the mission.<br/>
Some require a quicker responce due to time sensitive criteria.<br/>
" ]];

player createDiaryRecord ["patrol2", [ "Mobile HQ" , "
A mobile headquarters is a deployable vehicle capable of setting up a respawn and resupply point anywhere on the map.<br/>
To deploy the MHQ: jump in the drivers seat and select ""Deploy MHQ""<br/>
<br/>
The MHQ will automatically deploy an Ammobox the first time it is deployed. Make sure you pick the box up before leaving.<br/>
" ]];

player createDiaryRecord ["patrol2", [ "Lift Chopper" , "
If enabled, a large helicopter is capable of lifting EMPTY soft vehicles such as cars and trucks into the battlefield.<br/>
It also is capable lift the MHQ for quick deployment<br/>
Lift choppers can also air drop the vehicle on a location<br/>
<br/>
To Lift: hover over the vehicle at about 4-8m in height<br/>
Select lift from the action menu.<br/>
<br/>
To perform an airdrop of the vehicle: Fly at 170+ metres and release the vehicle.
" ]];

player createDiaryRecord ["patrol2", [ "Injury System" , "
Advanced injury system (AIS) is simple and great for gameplay.<br/>
Players can Drag wounded soldiers out of harms way<br/>
Players can apply first aid to get the wounded up and moving<br/>
Wounded players can crawl and fire off the last of their loaded rifle magazine wildly<br/>
Only medics can fully heal players<br/>
<br/>
ACE Wounding System can be turned on and will automatically disable AIS<br/>
For details on on ACE wounds, please see the ACE website.
" ]];

player createDiaryRecord ["patrol2", [ "IEDs" , "
IEDs (if enabled) will be a danager to all ground forces moving around the map.<br/>
Only Visibly detectable, an IED can cause alot of damage to vehicles and crew.<br/>
<br/>
If you spot a potential IED, stop the vehicle, approach on foot and attempt to either Defuse or Detonate it. Only then will it be safe to proceed.<br/>
It is not advisable to leave them as they will still pose a threat to other vehicles.
" ]];

player createDiaryRecord ["patrol2", [ "Containers" , "
Certain tasks require Containers to be loaded on a truck and transported to a target area.<br/>
<br/>
To perform this action, move a truck beside a container. Get out and move to the container.<br/>
An action on the container will give you the option of loading it onto the truck.<br/>
Once loaded you are able to move the truck around as long as the truck is not too damaged.<br/>
Once at the destination, you can unload the container by getting out of the truck and selecting the ""Unload"" action on the container.<br/>
<br/>
Be careful when unloading as the container will crush you if you are on the right side of the truck.<br/>
If the truck is too damaged, the container will fall off the truck.
" ]];

player createDiaryRecord ["patrol2", [ "Base Flag" , "
The Base Flag near the ammo box allows a player to either Halo Jump or Redeploy to a point in the battlefield.<br/>
<br/>
Halo Jump (High Altitude, Low Opening) involves the player selecting a position on a map, deploying them at the point at a height of 1500m. Deploy the parachute after decending to no less than 200m from the ground. The parachute is steerable.<br/>
<br/>
Redeploy allows a unit to move from the Base to a Deployed Mobile Headquarters in the field. There is no return.
" ]];

player createDiaryRecord ["patrol2", [ "Backpacks" , "
On vanilla servers, BIS Backpacks are avaiable at the backpack pile next to the base ammo box. (OA units only)<br/>
On ACE servers, ACE backpacks are included in the ammunition box.<br/>
<br/>
Vanilla: to use a backpack, select it from the pile and click the image to equip. To load ammunition into it, go the ammo box and in the gear menu, select the backpack and click ""Open Pack"" then simply add ammunition to it.<br/>
ACE: equip a backpack from the ammo box, then select some gear already loaded on you, then click the ""Pack"" button to store that item in your backpack.
" ]];

player createDiaryRecord ["patrol2", [ "Ammoboxes" , "
Ammoboxes contain all the weapons and ammunitions available to your unit.<br/>
Class restrictions apply on the type of weapons available to the player.<br/>
 e.g.<br/>
 - a Sniper has Sniper Rifles<br/>
 - a Machine gunner has machine guns<br/>
 - a Anti Armour has rocket launchers<br/>
Rank can also limit the range of weapons (if enabled) and will require you to rank up to get access to better weapons and technology<br/>
<br/>
Ammoboxes can be loaded into most transport vehicles, HMMWVs, and transport choppers.<br/>
This can be done at any supply point through the action menu ""Load Ammobox""<br/>
In the field the ammobox can be unloaded and for teams to access their weapons closer to the objective.<br/>
<br/>
Helicopters can also perform an Airdrop by simply flying at 160m+ from the terrain and Unloading the Ammobox.<br/>
" ]];

player createDiaryRecord ["patrol1", [ "Credits" , format["
Patrol Operations - %1<br/>
<br/>
Online Combat Battalion Australia for their support and testing of Patrol Operations has been vital in its success.<br/>
<br/>
Special thanks to:<br/>
- BIS for Arma Series<br/>
- BON_IF for alot of Code, Support and Inspiration from Taksitan Force<br/>
- XENO for Code and Inspiration from Domination 2<br/>
- Kochleffel for Vehicle And Squad Team Hud<br/>
- Code34 for Advanced Hint System and adaption of Vehicle/squad Hud<br/>
- [OCB]Kev for his knowledge and code examples<br/>
- Shuko for Task System and Position<br/>
- R3F for Respawn GUI and Logistics Code<br/>
- Ei8ght and Mike-USA for Sampled Base Layouts<br/>
- ArmA 2 Community for support and solutions<br/>
",toUpper worldname] ]];

player createDiaryRecord ["patrol1", [ "Mods" , format["
Patrol Operations - %1<br/>
Patrol Ops is an adaptable framework designed specifically for easy modification for other content mods and maps.<br/>
Already capable mods are: AAW, I44, Duala Units<br/>
Capable Maps: ALL MAPS AVAILABLE<br/>
Please see the Patrol Ops documentation on how to modify for further details.
",toUpper worldname] ]];

player createDiaryRecord ["patrol1", [ "ACE and ACRE" , format["
Patrol Operations supports ACE and ACRE modifications to ArmA 2<br/>
<br/>
ACE: A single Patrol Ops Mission PBO is able to boot on a server with or without ACE and will automatically adapt gameplay and equipment to match.<br/>
ACE version requires ACE and ACEX
<br/>
ACRE: In the Mission Parameters at startup, an option is available to add in ACRE radios to the weapons boxes<br/>
",toUpper worldname] ]];

player createDiaryRecord ["patrol1", [ "Gameplay" , format["
Patrol Operations - %1<br/>
<br/>
Key to Patrol Ops is to work as a team and have a strategy when approaching the objectives.<br/>
Missions are random and enemy aren't going to be exactly where you thing they will be.<br/>
<br/>
Remember to scan, advance and secure your locations as the enemy and their strength is random and even the mission maker cannot tell you exaclty what to expect.

",toUpper worldname] ]];

player createDiaryRecord ["patrol1", [ "Brief" , format["
Patrol Operations - %1<br/>
Patrol Ops is a dynamic, random mission series that is great for both Public play and Clan Tactical nights.<br/>
<br/>
Missions are randomly dynamic, with enemy force strength scaled to match the number of players connected so as to challenge players appropriatly.<br/>
Vanila, ACE and ACRE are supported in a single mission PBO and will adapt the gameplay and equipment to match the servers settings.<br/>
Player Class types denote access to specific gear and vehicles to strengthen the realism<br/>
<br/>
A focus on co-operative team based gameplay is the principle of Patrol Ops and on behalf of the Online Combat Battalion www.ocb.net.au, i hope you enjoy Patrol Ops 2<br/>By EightySix
",toUpper worldname] ]];

if(true) exitWith{};

