#define CEP_CACHE
#define RMM_DEBUG
//#define RMM_GTK
//#define RMM_HELP
#define RMM_MP_RIGHTS
#define RMM_NOMAD
//#define RMM_OSL
//#define RMM_OSOM
#define RMM_SETTINGS
#define RMM_WEATHER
