//#define RMM_NOMAD
//#define RMM_LOGISTICS
//#define RMM_TYRES
//#define RMM_SETTINGS
//#define RMM_REVIVE
//#define RMM_CNSTRCT
#define RMM_LOGBOOK
#define RMM_JIPMARKERS
#define RMM_AAR
#define RMM_TASKS